# Generated by Django 5.0.6 on 2026-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_family_submitted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['relation', 'name'], 'verbose_name': 'Member / સભ્ય', 'verbose_name_plural': 'Members / સભ્યો'},
        ),
        migrations.AddField(
            model_name='member',
            name='annual_income',
            field=models.CharField(blank=True, help_text='e.g. 3-5 Lakh, 5-10 Lakh', max_length=50, verbose_name='વાર્ષિક આવક / Annual Income'),
        ),
        migrations.AddField(
            model_name='member',
            name='any_disability',
            field=models.BooleanField(default=False, verbose_name='અપંગતા / Any Disability'),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], max_length=10, verbose_name='બ્લડ ગ્રૂપ / Blood Group'),
        ),
        migrations.AddField(
            model_name='member',
            name='disability_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='અપંગતા વિગત'),
        ),
        migrations.AddField(
            model_name='member',
            name='education_detail',
            field=models.CharField(blank=True, help_text='e.g. B.Com from Gujarat University 2020', max_length=200, verbose_name='શિક્ષણ વિગત / Education Detail'),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ઈ-મેઈલ / Email'),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('unmarried', 'અવિવાહિત / Unmarried'), ('married', 'વિવાહિત / Married'), ('widowed', 'વિધવા/વિધુર / Widowed'), ('divorced', 'છૂટાછેડા / Divorced')], default='unmarried', max_length=20, verbose_name='વૈવાહિક સ્થિતિ / Marital Status'),
        ),
        migrations.AddField(
            model_name='member',
            name='marriage_date',
            field=models.DateField(blank=True, null=True, verbose_name='લગ્ન તારીખ / Marriage Date'),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation_detail',
            field=models.CharField(blank=True, help_text='e.g. Software Engineer at TCS, Ahmedabad', max_length=200, verbose_name='કામ વિગત / Work Detail'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='જીવનસાથી નામ / Spouse Name'),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, verbose_name='WhatsApp નં.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='education',
            field=models.CharField(blank=True, choices=[('below_5th', 'Below 5th'), ('5th', '5th Pass'), ('8th', '8th Pass'), ('10th', '10th Pass (SSC)'), ('12th', '12th Pass (HSC)'), ('diploma', 'Diploma'), ('graduate', 'Graduate (B.A/B.Com/B.Sc)'), ('engineering', 'B.E / B.Tech'), ('medical', 'MBBS / Medical'), ('postgraduate', 'Post Graduate (M.A/M.Com/M.Sc)'), ('mba', 'MBA'), ('phd', 'PhD / Doctorate'), ('other', 'Other')], max_length=50, verbose_name='શિક્ષણ / Education'),
        ),
        migrations.AlterField(
            model_name='member',
            name='relation',
            field=models.CharField(choices=[('head', 'મુખ્ય / Head'), ('wife', 'પત્ની / Wife'), ('son', 'પુત્ર / Son'), ('daughter', 'પુત્રી / Daughter'), ('daughter_in_law', 'પુત્રવધૂ / Daughter-in-law'), ('son_in_law', 'જમાઈ / Son-in-law'), ('father', 'પિતા / Father'), ('mother', 'માતા / Mother'), ('brother', 'ભાઈ / Brother'), ('sister', 'બહેન / Sister'), ('grandfather', 'દાદા / Grandfather'), ('grandmother', 'દાદી / Grandmother'), ('grandson', 'પૌત્ર / Grandson'), ('granddaughter', 'પૌત્રી / Granddaughter'), ('uncle', 'કાકા / Uncle'), ('aunt', 'કાકી / Aunt'), ('other', 'અન્ય / Other')], max_length=50, verbose_name='સંબંધ / Relation'),
        ),
    ]
